### ISSUE TITLE
how to use with identityserver4 ?

### ISSUE THREAD

**Issue by aaguerra** [dontlaugh/auth0-rocket-rust-example#4]

**Comment by dontlaugh** [comment]
If you mean [this project](https://github.com/IdentityServer/IdentityServer4), it's going to require you to fork this project and make changes. I'm not familiar with IdentityServer4, but you will probably need to do something like

* fork this code
* create a dev instance of IdentityServer4
* determine how the callback routes are called from IdentityServer4 (they may be configurable, just like they are in Auth0)
* Determine the contents of the jwt that is returned from IdentityServer4

This project only supports Auth0. One of the things Auth0 gives you is a **login page** for a username/password. Our login link points you there. If IdentityServer4 doesn't give you this, you will also need to create a new login page.

Unfortunately, implmentations of OAuth can vary pretty widely, so it will definitely require some work to support.
