### ISSUE TITLE
custom_derive feature has been removed

### ISSUE THREAD

**Issue by wenewzhang** [dontlaugh/auth0-rocket-rust-example#5]
error[E0557]: feature has been removed
 --> src/main.rs:3:12
  |
3 | #![feature(custom_derive)]
  |            ^^^^^^^^^^^^^
  |
note: subsumed by `#[proc_macro_derive]`
 --> src/main.rs:3:12
  |
3 | #![feature(custom_derive)]
  |            ^^^^^^^^^^^^^

error: aborting due to previous error

For more information about this error, try `rustc --explain E0557`.
error: Could not compile `changes`.

To learn more, run the command again with --verbose.

**Comment by dontlaugh** [comment]
@wenewzhang I upgraded most of the libraries and moved the code to 2018 edition Rust. Can you try latest `master`?

**Comment by wenewzhang** [comment]
it's works now
